### ISSUE TITLE
Are the docs now full-width by design?

### ISSUE THREAD

**Issue by rowanwins** [Turfjs/turf-www#107]
Gday @DenisCarriere 

Just had a look at the docs and on the API page they are now spanning the full-width of the page rather than having some white padding on either side, it looks like this is a result of [your commit](https://github.com/Turfjs/turf-www/commit/36f542b154b24cf48c8b034f8e27ca767726381f)

Did you do this on purpose?
![alt tag](https://www.dropbox.com/s/74hpk0o3v6pzs5k/paddingGone.jpeg?dl=1)

I think they look a bit more cluttered and less readable with the padding gone so are you happy for me to revert them back to have some breathing space?

**Comment by DenisCarriere** [comment]
No this wasn't on purpose, de-conflicting this PR https://github.com/Turfjs/turf-www/pull/95 might of overlapped on new some new commits.

Feel free to re-add the padding if I "screwed it up" 👍.

Ideally ⭐️ .. the CSS should be using `display: flex` instead of `position: fixed`.. the current CSS is pretty clunky.. hence all the required padding & margin hacks.

**Comment by rowanwins** [comment]
Gday @DenisCarriere 

Yeah the css is a bit clunky, I'll take a squiz and get it a bit more streamlined.

**Comment by DenisCarriere** [comment]
No rush 👍 as long as the padding is fixed, I was getting confused applying margins & paddings to the divs.
