### ISSUE TITLE
Many links appear to be broken on the document site.

### ISSUE THREAD

**Issue by tpgus** [Turfjs/turf-www#212]
Many links appear to be broken on the document site.

This issue is not page specific, and is seen on multiple pages.

Maybe, it's a problem that occurred after the https://github.com/Turfjs/turf-www/commit/e885325eacef1b6b7cd63c04c71f4e26a8c19fcb commit, but I'm not sure.

**Comment by smallsaucepan** [comment]
Hi @tpgus. Thanks for pointing these out. It's a known issue I haven't had time to fix yet. Would welcome a PR if you have time?

Briefly, these unconverted links are in the documentation for the most recent relase (7.1.0): https://turfjs.org/docs/api/area There might even be a few in the 6.5.0 docs.

Most (or all) of these should be fixed in the "next" documentation - reflecting the latest development code: https://turfjs.org/docs/next/api/area

It should be fairly easy (though a bit tedious) to hand edit the Markdown (MDX) files for the older documentation. Once the older documents are versioned, they're just static files that can be edited like any other Markdown.

For example, copying the `[link](url)` text from the working version `docs/api/area.mdx` to the broken version `versioned_docs/version-7.1.0/api/area.mdx` would resolve the issue next time the website was published.

Alternatively, we can do nothing and when we release 7.2.0 effectively snapshotting the better "next" documentation, the crumby 7.1.0 documentation will become less prominent.

**Comment by tpgus** [comment]
Thank you @smallsaucepan for your detailed answer.

As you mentioned, it's more of a tedious task rather than a difficult one 😅, 
but it definitely seems like a task worth working on.

before correcting the broken links, I have a few questions.

1. Is it correct that the underlined part of the "bbox" in the image attached above is not subject to correction?
   wasn't it a link before? (Looks like I might have misunderstood.)

2. Is it okay to fix only the links that are supposed to function as 'link' but are either broken or incorrectly formatted (such as {@link Feature})?
(in the 'next' document, I noticed that the `<ul>` tag was removed in the sections describing the 'returns' for each module. However, Would it be okay not to include it in this task.)
