### ISSUE TITLE
Fill out /docs "Home" page

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-www#45]
This page needs words and such: http://turfjs.org/docs/

**Comment by franckl** [comment]
The link to "api docs" on the example page is incorrect at the moment, it should be http://turfjs.org/static/docs

**Comment by lyzidiamond** [comment]
A first pass at some content for this page: https://gist.github.com/lyzidiamond/ab6bf218fff2d9e580ad

@tmcw @morganherlocker

**Comment by lyzidiamond** [comment]
Bumping this: @tmcw @morganherlocker would y'all mind taking a quick look before I push?

**Comment by morganherlocker** [comment]
@lyzidiamond 

- We can probably cut this [1st section](https://gist.github.com/lyzidiamond/ab6bf218fff2d9e580ad#turfjs-api-documentation). I don't think it's necessary to document the documentation.
- "Turf also has some helper methods for creating features in specific instances, like turf.random and turf.bbox-polygon. Most of the rest of the methods in Turf are for conducting spatial operations and/or analysis; these methods both take GeoJSON as inputs and return GeoJSON as outputs." << I think we can cut this or move it somewhere else. 
- "Turf has four main internal methods for creating features:" << kind of hard to tell that these are just returning plain ole geojson and that people do not have to use them. This is explained in the current Data section of the docs http://turfjs.org/examples.html
- The current docs state "Turf expects the data to be standard WGS84 longitude, latitude coordinates", which is really important

I'm honestly a bit torn on going into so much detail about GeoJSON here. I think [the spec](http://geojson.org/) does a really good job of explaining it, and reading [this page](http://geojson.org/geojson-spec.html) is pretty much the bare minimum that users **must** do to use Turf effectively.

**Comment by morganherlocker** [comment]
> Turf is built from new mathematical algorithms behind spatial analysis operations, so it can conduct tasks quickly and efficiently.

This is not really accurate, since most of turf is actually built on very established algorithms from the academic world. Might want to cut this as to not step on any toes.

**Comment by lyzidiamond** [comment]
@morganherlocker: that's super helpful!

Just as a brain picking exercise: what exactly would we like to include on this page?

**Comment by lyzidiamond** [comment]
Also, on GeoJSON:

@tmcw and I had talked specifically about adding a more thorough explanation of GeoJSON somewhere precisely because the spec is confusing if you're approaching it for the first time. It can live elsewhere, though, if we can find a better place for it.

**Comment by tmcw** [comment]
:+1: for mentioning GeoJSON but leaving the big introduction to a separate page where it has more space to breathe, and linking between.

**Comment by morganherlocker** [comment]
@lyzidiamond originally this had 

1. what is turf
2. installation
3. data

2 is on the homepage now, but I think the other two sections are still good. Basically I really like what you have, but want to cut or move anything that's not super important, since this is the opening page of the API and [people hate reading](http://www.joelonsoftware.com/uibook/chapters/fog0000000062.html). 

Update (just saw your comment): I think it would make sense to have a page on working with data, but if we are going to have this much detail, then it should probably be separate. This would apply for things like projections, JS specific stuff, installing node.js, etc.  These could also be bundled up as independent guides. 

The other alternative would be to help improve the GeoJSON spec itself. If it is unclear and not useful to its target audience, then it really should be modified.

**Comment by lyzidiamond** [comment]
Alright, this is super pared down. I just kept the "What is Turf?" section and then added a "Data in Turf" section that pulls directly from the /examples.html page: https://gist.github.com/lyzidiamond/a9c5ac64d21d416ce9c9

@tmcw @morganherlocker

**Comment by morganherlocker** [comment]
@lyzidiamond This looks great :+1:

**Comment by lyzidiamond** [comment]
This is deployed: https://turfjs.org/static/docs

Closing! :dancer: :briefcase: :walking:
