### ISSUE TITLE
Categorize modules

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-www#49]
/cc @morganherlocker @lyzidiamond 

How do we provide a useful layer of navigation on top of docs? There's no native JSDoc tag for this, though we could abuse something like [summary](http://usejsdoc.org/tags-summary.html).

I think the first bet is to try out the [category plugin](https://github.com/ErnstHaagsman/jsdoc-plugins).

**Comment by tmcw** [comment]
Original categories from @jvrousseau :+1: 

```
  - id: geometry
    name: geometry
  - id: joins
    name: joins
  - id: data
    name: data
  - id: measurement
    name: measurement
  - id: interpolation
    name: interpolation
  - id: classification
    name: classification
  - id: aggregation
    name: aggregation
  - id: transformation
    name: transformation
  - id: misc
    name: misc
```

This sounds good, some small changes:

* geometry objects
* interpolation
* analysis
* helpers
* predicates

Thoughts @morganherlocker @lyzidiamond @sgillies ? trying to match as much as possible from http://resources.arcgis.com/en/help/main/10.1/index.html#//000v000000v7000000 http://toblerity.org/shapely/manual.html#set-theoretic-methods http://geos.osgeo.org/doxygen/namespaces.html

**Comment by morganherlocker** [comment]
I'm pretty happy with the original categories (which come from the [turf readme](https://github.com/Turfjs/turf#features)), but

- data should be something more descriptive like "statistics"
- not crazy about the joins category and I think these 3 could be put into other categories
- probably want to add a boolean category (maybe a word thats less jargon-y though?)

The new ones:

- analysis: too vague I think. I think most things in this category could be broken into more specific categories (since the entire library is "analysis" in one sense or another).
- helpers: I like this. Right now I am treating things like turf-meta as internal-only or separate, but they might have a place here along with things like turf-flip.
- predicates: probably want to dumb that one down a bit (I had to look up what the technical meaning you had in mind was). Also, I think the categories should be more functional groupings rather than technical.

I think we should follow Shapely just about anywhere it has an opinion on what we are doing. GEOS has a notoriously confusing structure, so we probably want to avoid it. Arc has a pretty reasonable grouping in my opinion, but its a bit coarse (since arcpy does way more things):

![](http://i.stack.imgur.com/Va1Ff.png)

**Comment by lyzidiamond** [comment]
I like the idea of keeping this simple, but I'm having trouble identifying which is the ideal taxonomy. I defer to y'all's knowledge on this one.

**Comment by tmcw** [comment]
Done
