### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by lyzidiamond** [Turfjs/turf-www#87]
Now that turf is restructured, does this change how documentation is generated? I would like to:

- [x] generate new documentation
- [ ] update this repo with documentation on how to generate documentation

@tmcw @morganherlocker @tcql

**Comment by caseypt** [comment]
Consider adding documentation to describe the purpose of the `turf-junkyard` org. Are the repos there considered deprecated?

**Comment by morganherlocker** [comment]
@caseypt all repos in turf-junkyard are no longer maintained. That said, the majority of turf modules have been moved [inside the master turf repo, here](https://github.com/Turfjs/turf/tree/master/packages). Mostly, this was just a change in internal project structure, rather than a change that should be noticed by turf users.

**Comment by caseypt** [comment]
@morganherlocker Thanks for the clarification.

**Comment by tmcw** [comment]
-> FAQ: https://github.com/Turfjs/turf/wiki/FAQ
