### ISSUE TITLE
Lots of links broken

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf-www#96]
Seems like a lot of links are broken since the TurfJS html page structure is a bit different.

Previous URL

- http://turfjs.org/docs/#intersect

New URL

- http://turfjs.org/docs.html#intersect

Two ways to fix this

1. Find and hunt down all the reference links to TurfJS

2. Change the HTML structure back to `/docs/` instead of `/docs.html`.

Option 2 is a lot less work.

CC: @rowanwins

**Comment by rowanwins** [comment]
Gday @DenisCarriere 

Yeah I only noticed those links in the TS last night. 

The move from the docs for to the flatter url was intentional to have a more consistent url pattern but if it's going to cause too many issues then I guess it can be changed back. 

I'm with it either way, let me know your preference and I'll get it sorted

**Comment by DenisCarriere** [comment]
Well the issue isn't just my TS links, but also anyone else with a URL that was referencing the old style of URL path.

I personally prefer the URL's without `.html`.

If you could change it back to `/docs/` that is the easiest path.

Even if you're not using Typescript you can still have the benefits of code hinting.


![image](https://cloud.githubusercontent.com/assets/550895/22760496/ad7d7ad2-ee24-11e6-9d28-769685ac9ae0.png)

**Comment by rowanwins** [comment]
Resolved by #97
